//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunStack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int QuestionId { get; set; }
        public string Question1 { get; set; }
        public string Postedby { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public IEnumerable<Question> Questions { get; set; }

        public virtual ICollection<Answer> Answers { get; set; }
    }
}
